module.exports = {
  "package.json": require("../templates/package.js"),
  ".gitignore": require("../templates/gitignore.js"),
  "prettier.config.js": require("../templates/prettier.config"),
  "webpack.config.js": require("../templates/webpack.config"),
  ".babelrc": require("../templates/babelrc"),
  "src/App.css": require("../templates/src/App.css"),
  "src/App.js": require("../templates/src/App.js"),
  "src/index.css": require("../templates/src/index.css"),
  "src/index.js": require("../templates/src/index"),
  "src/store/store.js": require("../templates/src/store/store"),
  "src/store/action/index.js": require("../templates/src/store/action/index"),
  "src/store/reducer/index.js": require("../templates/src/store/reducer/index"),
  "src/store/type/index.js": require("../templates/src/store/type/index"),
  "src/screens/About.js": require("../templates/src/screens/About"),
  "src/screens/Home.js": require("../templates/src/screens/Home"),
  "public/index.html": require("../templates/public/index.html"),
};
